name: Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Lint (web)
        run: npm -w web run lint

      - name: Typecheck (backend)
        run: npm -w backend run typecheck

      - name: Build (web)
        run: npm -w web run build
