name: No Legacy Frontends

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set BASE ref
        id: base
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "base=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
          else
            echo "base=main" >> $GITHUB_OUTPUT
          fi

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Run legacy frontends check
        env:
          GITHUB_BASE_REF: ${{ steps.base.outputs.base }}
        run: scripts/check-no-legacy-refs.sh
